# Allow kube-rbac-proxies to create tokenreviews to check Prometheus identity when scraping metrics.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-vpc-block-kube-rbac-proxy-binding
subjects:
  - kind: ServiceAccount
    name: ibm-vpc-block-controller-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: ClusterRole
  name:  ibm-vpc-block-kube-rbac-proxy-role
  apiGroup: rbac.authorization.k8s.io
