apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: vpc-block-snapshot
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: vpc.block.csi.ibm.io
deletionPolicy: Delete
